### ISSUE TITLE
Set the default server url and login user:pass to the openmrs demo server.

### ISSUE THREAD

**Issue by harshadura** [Undo1/OpenMRS-iOS#14]

**Comment by harshadura** [comment]
hey perway, good job.
but i thought this feature would available within the production app too. Unfortunately seems its not.  Please change it to default config for login also visible in the fields. so can use it future releases.

PS: I am sure lots of (new coming) people will ask questions about the login details, So worried about it since the app already published at appstore.

**Comment by Undo1** [comment]
@harshadura, done! :)
