### ISSUE TITLE
green background ios app splashes

### ISSUE THREAD

**Issue by uzanysa** [Undo1/OpenMRS-iOS#19]
![openmrs ios splash 6](https://cloud.githubusercontent.com/assets/10286177/5568511/26ee0582-8f98-11e4-83f8-edeeb5435749.png)
![openmrs ios splash 7](https://cloud.githubusercontent.com/assets/10286177/5568512/26fa79d4-8f98-11e4-9e73-1f9993db2944.png)

**Comment by harshadura** [comment]
nice 1, thx
